version: "3"

services:
    cdn:
        container_name: cdn
        build: .
        restart: unless-stopped
        volumes:
            - ./cdn_root:/usr/local/bin/cdn_root
        ports:
            - 4200:41890
        networks:
            - app_network
        environment:
            - BIND_ADDRESS=0.0.0.0

networks:
    app_network:
        external: true
